[package]
name = "end_to_end"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-std = { version = "0.5.0", features = ["parallel"] }
ark-ec = { version = "0.5.0", features = ["parallel"] }
ark-bn254 = "0.5.0"
ark-isep = { path = "../.." }